//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Rut { get; set; }
        public string Sexo { get; set; }
        public int Mail { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public int DoctorId { get; set; }
        public string Observacion { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
